version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      -  npm run build

artifacts:
  type: zip
  files:
    - package.json
    - Procfile
    - package-lock.json
    - 'dist/**/*'


# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: latest
#     commands:
#       - npm install -g typescript
#       - npm install
#   build:
#     commands:
#       - tsc

# artifacts:
#   files:
#     - package.json
#     - package-lock.json
#     - 'build/**/*'
#   discard-paths: yes